version: "3"

services: 
  shifts_api:
    build: api/.
    container_name: shifts-api
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgres/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks: 
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@smartcat.io
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks: 
      - postgres
    restart: unless-stopped

  etl:
    build:
      context: etl/.
      dockerfile: Dockerfile
    container_name: etl
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - shifts_api
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
