server:
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  retry:
    instances:
      shiftsApiClientRetryPolicy:
        maxRetryAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        resultPredicate: com.example.etl.predicate.ConditionalRetryPredicate